apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: kibana
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: kibanaTemplate
    creationTimestamp: null
    generation: 1
    labels:
      app: kibana
    name: kibana
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: kibanaTemplate
    creationTimestamp: null
    labels:
      app: kibana
    name: kibana
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: kibana:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: kibana
      git:
        ref: master
        uri: ${SOURCE_REPOSITORY_URL}
      secrets: []
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: rhel7:latest
      type: Docker
    triggers:
    - github:
        secret: ${GITHUB_WEBHOOK_SECRET}
      type: GitHub
    - generic:
        secret: ${GENERIC_WEBHOOK_SECRET}
      type: Generic
    - type: ConfigChange
  status:
    lastVersion: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: kibanaTemplate
    creationTimestamp: null
    labels:
      app: kibana
    name: kibana
  spec:
    replicas: 1
    selector:
      app: kibana
      deploymentconfig: kibana
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: kibanaTemplate
        creationTimestamp: null
        labels:
          app: kibana
          deploymentconfig: kibana
      spec:
        containers:
        - name: kibana
          image: kibana:latest
          ports:
          - containerPort: 5601
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - kibana
        from:
          kind: ImageStreamTag
          name: kibana:latest
      type: ImageChange
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: kibanaTemplate
    creationTimestamp: null
    labels:
      app: kibana
    name: kibana
  spec:
    ports:
    - name: 5601-tcp
      port: 5601
      protocol: TCP
      targetPort: 5601
    selector:
      app: kibana
      deploymentconfig: kibana
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}

parameters:
-
  name: GITHUB_WEBHOOK_SECRET
  displayName: GitHub Webhook Secret
  description: A secret string used to configure the GitHub webhook.
  generate: expression
  from: "[a-zA-Z0-9]{40}"
-
  name: GENERIC_WEBHOOK_SECRET
  displayName: Generic Webhook Secret
  description: A secret string used to configure the Generic webhook.
  generate: expression
  from: "[a-zA-Z0-9]{40}"

- name: SOURCE_REPOSITORY_URL
  description: The URL of the Git repository with the Dockerfile
  required: true
  value: http://github.com/jnordell/ocp3-elk.git
